### ISSUE TITLE
画面の下にボタンを追加する

### ISSUE THREAD

**Issue by wada811** [char-i3/MemoChar#1]
- Twitter
- Instagram
- 共有
- コピー

**Comment by wada811** [comment]
ボタンを追加したぞ！！ · char-i3/MemoChar@f088f89 https://github.com/char-i3/MemoChar/commit/f088f89b34b13cfe4658b3201b39f65cf6f90dc6

@char-i3 
追加で保存ボタンも増やしたよ！すごい！

アイコンはここからダウンロードしてた！
Social media Icons in Material Design Style https://icons8.com/icon/set/social-media/material

**Comment by wada627** [comment]
@wada811 
ちゃぴ、ちゅぉーい
